# Generated by Django 3.1.7 on 2021-04-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='No')),
                ('startDate', models.DateField(blank=True, verbose_name='読始日')),
                ('endDate', models.DateField(blank=True, verbose_name='読始日')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('categoly', models.CharField(blank=True, max_length=255, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='メモ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='masterManagement.book', verbose_name='書籍')),
            ],
        ),
    ]
