# Generated by Django 3.1.7 on 2021-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterManagement', '0002_auto_20210401_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='読始日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='読始日'),
        ),
    ]
