name: Deploy to EC2  
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [ main ]
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
    # 保存したシークレットたちを環境変数に設定
      env:
        SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run:
        echo "$SSH_SECRET_KEY" > ssh_secret_key && chmod 600 ssh_secret_key && ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i ssh_secret_key "cd /home/${EC2_USER}/django-reading-record && git pull origin main"
