name: Deploy to EC2  
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
    # 保存したシークレットたちを環境変数に設定
      env:
        SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: 
        echo "$SSH_SECRET_KEY" > secret_key && chmod 600 secret_key
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key
        cd /home/ec2-user/django-reading-record && git pull origin main
